CREATE DATABASE IF NOT EXISTS PersonDB;
USE PersonDB;

CREATE TABLE IF NOT EXISTS Person (
    id INTEGER UNSIGNED PRIMARY KEY,
    firstName VARCHAR(100) NOT NULL,
    middleName VARCHAR(100),
    lastName VARCHAR(100) NOT NULL
) ENGINE=InnoDB;
